# Generated by Django 4.2.7 on 2024-03-31 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_bid_auction_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='temporary_winner',
            field=models.BooleanField(default=False),
        ),
    ]
