# Generated by Django 4.2.7 on 2024-03-31 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auction_temporary_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='temporary_winner',
            field=models.IntegerField(default=0),
        ),
    ]
