# Generated by Django 4.2.7 on 2024-03-31 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_alter_auction_temporary_winner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='reviewer',
            new_name='commenter',
        ),
    ]
