# Generated by Django 4.2.7 on 2024-04-30 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_posts_follows'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Follows',
            new_name='Follow',
        ),
        migrations.RenameModel(
            old_name='Posts',
            new_name='Post',
        ),
    ]
