# Generated by Django 4.2.7 on 2024-05-29 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
